import { IAlbum, IAlbums } from "../models/IAlbum";
import { CdType, FocusPerformersType, SongType, SONGS } from "../utils/constants";

const imagaomoideninarumade: IAlbum = {
  title: "今が思い出になるまで",
  number: "4",
  release: "2019-04-17",
  hasArtworks: true,
  artworks: {
    [CdType.L]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.A]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.B]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.T]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONGS["ありがちな恋愛"].title,
      key: SONGS["ありがちな恋愛"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Lead,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONGS["逃げ水"].title,
      key: SONGS["逃げ水"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONGS["いつかできるから今日できる"].title,
      key: SONGS["いつかできるから今日できる"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONGS["シンクロニシティ"].title,
      key: SONGS["シンクロニシティ"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONGS["ジコチューで行こう!"].title,
      key: SONGS["ジコチューで行こう!"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONGS["帰り道は遠回りしたくなる"].title,
      key: SONGS["帰り道は遠回りしたくなる"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONGS["アンダー"].title,
      key: SONGS["アンダー"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONGS["My rule"].title,
      key: SONGS["My rule"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONGS["新しい世界"].title,
      key: SONGS["新しい世界"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONGS["三角の空き地"].title,
      key: SONGS["三角の空き地"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONGS["日常"].title,
      key: SONGS["日常"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONGS["もし君がいなければ"].title,
      key: SONGS["もし君がいなければ"].key,
      inCdType: [CdType.L],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONGS["キスの手裏剣"].title,
      key: SONGS["キスの手裏剣"].key,
      inCdType: [CdType.L],
      type: SongType.FourthGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONGS["Against"].title,
      key: SONGS["Against"].key,
      inCdType: [CdType.L],
      type: SongType.FirstGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONGS["つづく"].title,
      key: SONGS["つづく"].key,
      inCdType: [CdType.L],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONGS["頬杖をついては眠れない"].title,
      key: SONGS["頬杖をついては眠れない"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONGS["ぽっち党"].title,
      key: SONGS["ぽっち党"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONGS["僕の衝動"].title,
      key: SONGS["僕の衝動"].key,
      inCdType: [CdType.A],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONGS["スカウトマン"].title,
      key: SONGS["スカウトマン"].key,
      inCdType: [CdType.A],
      type: SongType.SecondGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONGS["さゆりんご募集中"].title,
      key: SONGS["さゆりんご募集中"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONGS["ゴルゴンゾーラ"].title,
      key: SONGS["ゴルゴンゾーラ"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONGS["トキトキメキメキ"].title,
      key: SONGS["トキトキメキメキ"].key,
      inCdType: [CdType.B],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONGS["未来の答え"].title,
      key: SONGS["未来の答え"].key,
      inCdType: [CdType.B],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONGS["もうすぐ～ザンビ伝説～"].title,
      key: SONGS["もうすぐ～ザンビ伝説～"].key,
      inCdType: [CdType.T],
      type: SongType.Special,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONGS["キャラバンは眠らない"].title,
      key: SONGS["キャラバンは眠らない"].key,
      inCdType: [CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONGS["ライブ神"].title,
      key: SONGS["ライブ神"].key,
      inCdType: [CdType.T],
      type: SongType.SecondGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 27,
      title: SONGS["自分じゃない感じ"].title,
      key: SONGS["自分じゃない感じ"].key,
      inCdType: [CdType.T],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

const bokudakenokimi: IAlbum = {
  title: "僕だけの君〜Under Super Best〜",
  number: "U",
  release: "2018-01-10",
  hasArtworks: true,
  artworks: {
    [CdType.L1]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.L2]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.T]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONGS["左胸の勇気"].title,
      key: SONGS["左胸の勇気"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONGS["狼に口笛を"].title,
      key: SONGS["狼に口笛を"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONGS["涙がまだ悲しみだった頃"].title,
      key: SONGS["涙がまだ悲しみだった頃"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONGS["春のメロディー"].title,
      key: SONGS["春のメロディー"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONGS["13日の金曜日"].title,
      key: SONGS["13日の金曜日"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONGS["扇風機"].title,
      key: SONGS["扇風機"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONGS["初恋の人を今でも"].title,
      key: SONGS["初恋の人を今でも"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONGS["生まれたままで"].title,
      key: SONGS["生まれたままで"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONGS["ここにいる理由"].title,
      key: SONGS["ここにいる理由"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONGS["あの日 僕は咄嗟に嘘をついた"].title,
      key: SONGS["あの日 僕は咄嗟に嘘をついた"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONGS["君は僕と会わない方がよかったのかな"].title,
      key: SONGS["君は僕と会わない方がよかったのかな"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONGS["別れ際、もっと好きになる"].title,
      key: SONGS["別れ際、もっと好きになる"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONGS["嫉妬の権利"].title,
      key: SONGS["嫉妬の権利"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONGS["不等号"].title,
      key: SONGS["不等号"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONGS["シークレットグラフィティー"].title,
      key: SONGS["シークレットグラフィティー"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONGS["ブランコ"].title,
      key: SONGS["ブランコ"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONGS["風船は生きている"].title,
      key: SONGS["風船は生きている"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONGS["アンダー"].title,
      key: SONGS["アンダー"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONGS["My rule"].title,
      key: SONGS["My rule"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONGS["自由の彼方"].title,
      key: SONGS["自由の彼方"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONGS["欲望のリインカーネーション"].title,
      key: SONGS["欲望のリインカーネーション"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONGS["君が扇いでくれた"].title,
      key: SONGS["君が扇いでくれた"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONGS["自分のこと"].title,
      key: SONGS["自分のこと"].key,
      inCdType: [CdType.L2],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONGS["自惚れビーチ"].title,
      key: SONGS["自惚れビーチ"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONGS["その女"].title,
      key: SONGS["その女"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONGS["誰よりそばにいたい"].title,
      key: SONGS["誰よりそばにいたい"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

const umaretekara: IAlbum = {
  title: "生まれてから初めて見た夢",
  number: "3",
  release: "2017-05-24",
  hasArtworks: true,
  artworks: {
    [CdType.A]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.B]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.L]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.T]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONGS["裸足でSummer"].title,
      key: SONGS["裸足でSummer"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONGS["サヨナラの意味"].title,
      key: SONGS["サヨナラの意味"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONGS["インフルエンサー"].title,
      key: SONGS["インフルエンサー"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONGS["シークレットグラフィティー"].title,
      key: SONGS["シークレットグラフィティー"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONGS["ブランコ"].title,
      key: SONGS["ブランコ"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONGS["風船は生きている"].title,
      key: SONGS["風船は生きている"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONGS["スカイダイビング"].title,
      key: SONGS["スカイダイビング"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONGS["三番目の風"].title,
      key: SONGS["三番目の風"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONGS["君が扇いでくれた"].title,
      key: SONGS["君が扇いでくれた"].key,
      inCdType: [CdType.L],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONGS["思い出ファースト"].title,
      key: SONGS["思い出ファースト"].key,
      inCdType: [CdType.L],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONGS["設定温度"].title,
      key: SONGS["設定温度"].key,
      inCdType: [CdType.L],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONGS["孤独な青空"].title,
      key: SONGS["孤独な青空"].key,
      inCdType: [CdType.L],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONGS["僕だけの光"].title,
      key: SONGS["僕だけの光"].key,
      inCdType: [CdType.L],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONGS["人生を考えたくなる"].title,
      key: SONGS["人生を考えたくなる"].key,
      inCdType: [CdType.L],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONGS["意外BREAK"].title,
      key: SONGS["意外BREAK"].key,
      inCdType: [CdType.L],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONGS["Rewindあの日"].title,
      key: SONGS["Rewindあの日"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONGS["ごめんね、スムージー"].title,
      key: SONGS["ごめんね、スムージー"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONGS["醜い私"].title,
      key: SONGS["醜い私"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONGS["オフショアガール"].title,
      key: SONGS["オフショアガール"].key,
      inCdType: [CdType.A],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONGS["君に贈る花がない"].title,
      key: SONGS["君に贈る花がない"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONGS["白米様"].title,
      key: SONGS["白米様"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONGS["硬い殻のように抱きしめたい"].title,
      key: SONGS["硬い殻のように抱きしめたい"].key,
      inCdType: [CdType.B],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONGS["満月が消えた"].title,
      key: SONGS["満月が消えた"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONGS["ワタボコリ"].title,
      key: SONGS["ワタボコリ"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONGS["ないものねだり"].title,
      key: SONGS["ないものねだり"].key,
      inCdType: [CdType.B],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONGS["Another Ghost"].title,
      key: SONGS["Another Ghost"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 27,
      title: SONGS["あの教室"].title,
      key: SONGS["あの教室"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 28,
      title: SONGS["流星ディスコティック"].title,
      key: SONGS["流星ディスコティック"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 29,
      title: SONGS["忘却と美学"].title,
      key: SONGS["忘却と美学"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 30,
      title: SONGS["2度目のキスから"].title,
      key: SONGS["2度目のキスから"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 31,
      title: SONGS["命の真実 ミュージカル「林檎売りとカメムシ」"].title,
      key: SONGS["命の真実 ミュージカル「林檎売りとカメムシ」"].key,
      inCdType: [CdType.T],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 32,
      title: SONGS["行くあてのない僕たち"].title,
      key: SONGS["行くあてのない僕たち"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 33,
      title: SONGS["当たり障りのない話"].title,
      key: SONGS["当たり障りのない話"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

const sorezorenoisu: IAlbum = {
  title: "それぞれの椅子",
  number: "2",
  release: "2016-05-25",
  hasArtworks: true,
  artworks: {
    [CdType.A]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.B]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.C]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.D]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.T]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONGS["命は美しい"].title,
      key: SONGS["命は美しい"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONGS["太陽ノック"].title,
      key: SONGS["太陽ノック"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONGS["今、話したい誰かがいる"].title,
      key: SONGS["今、話したい誰かがいる"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONGS["きっかけ"].title,
      key: SONGS["きっかけ"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONGS["太陽に口説かれて"].title,
      key: SONGS["太陽に口説かれて"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONGS["欲望のリインカーネーション"].title,
      key: SONGS["欲望のリインカーネーション"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONGS["悲しみの忘れ方"].title,
      key: SONGS["悲しみの忘れ方"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONGS["空気感"].title,
      key: SONGS["空気感"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONGS["光合成希望"].title,
      key: SONGS["光合成希望"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONGS["無表情"].title,
      key: SONGS["無表情"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONGS["あらかじめ語られるロマンス"].title,
      key: SONGS["あらかじめ語られるロマンス"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONGS["隙間"].title,
      key: SONGS["隙間"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONGS["急斜面"].title,
      key: SONGS["急斜面"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONGS["羽根の記憶"].title,
      key: SONGS["羽根の記憶"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONGS["乃木坂の詩"].title,
      key: SONGS["乃木坂の詩"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONGS["Threefold choice"].title,
      key: SONGS["Threefold choice"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONGS["低体温のキス"].title,
      key: SONGS["低体温のキス"].key,
      inCdType: [CdType.B],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONGS["遥かなるブータン"].title,
      key: SONGS["遥かなるブータン"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONGS["ポピパッパパー"].title,
      key: SONGS["ポピパッパパー"].key,
      inCdType: [CdType.B],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONGS["制服を脱いでサヨナラを…"].title,
      key: SONGS["制服を脱いでサヨナラを…"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONGS["憂鬱と風船ガム"].title,
      key: SONGS["憂鬱と風船ガム"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONGS["立ち直り中"].title,
      key: SONGS["立ち直り中"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONGS["失恋したら、顔を洗え!"].title,
      key: SONGS["失恋したら、顔を洗え!"].key,
      inCdType: [CdType.C],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONGS["かき氷の片想い"].title,
      key: SONGS["かき氷の片想い"].key,
      inCdType: [CdType.C],
      type: SongType.SecondGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONGS["大人への近道"].title,
      key: SONGS["大人への近道"].key,
      inCdType: [CdType.C],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONGS["君は僕と会わない方がよかったのかな"].title,
      key: SONGS["君は僕と会わない方がよかったのかな"].key,
      inCdType: [CdType.C],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 27,
      title: SONGS["別れ際、もっと好きになる"].title,
      key: SONGS["別れ際、もっと好きになる"].key,
      inCdType: [CdType.C],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 28,
      title: SONGS["嫉妬の権利"].title,
      key: SONGS["嫉妬の権利"].key,
      inCdType: [CdType.C],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 29,
      title: SONGS["不等号"].title,
      key: SONGS["不等号"].key,
      inCdType: [CdType.C],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 30,
      title: SONGS["環状六号線"].title,
      key: SONGS["環状六号線"].key,
      inCdType: [CdType.D],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 31,
      title: SONGS["口約束"].title,
      key: SONGS["口約束"].key,
      inCdType: [CdType.D],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 32,
      title: SONGS["ロマンティックいか焼き"].title,
      key: SONGS["ロマンティックいか焼き"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 33,
      title: SONGS["ハウス!"].title,
      key: SONGS["ハウス!"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 34,
      title: SONGS["そんなバカな…"].title,
      key: SONGS["そんなバカな…"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 35,
      title: SONGS["シャキイズム"].title,
      key: SONGS["シャキイズム"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 36,
      title: SONGS["ロマンスのスタート"].title,
      key: SONGS["ロマンスのスタート"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

const tomeinairo: IAlbum = {
  title: "透明な色",
  number: "1",
  release: "2015-01-27",
  hasArtworks: true,
  artworks: {
    [CdType.A]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.B]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.C]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONGS["OVERTURE"].title,
      key: SONGS["OVERTURE"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONGS["ぐるぐるカーテン"].title,
      key: SONGS["ぐるぐるカーテン"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONGS["おいでシャンプー"].title,
      key: SONGS["おいでシャンプー"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONGS["走れ!Bicycle"].title,
      key: SONGS["走れ!Bicycle"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONGS["制服のマネキン"].title,
      key: SONGS["制服のマネキン"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONGS["君の名は希望"].title,
      key: SONGS["君の名は希望"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONGS["ガールズルール"].title,
      key: SONGS["ガールズルール"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONGS["バレッタ"].title,
      key: SONGS["バレッタ"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONGS["気づいたら片想い"].title,
      key: SONGS["気づいたら片想い"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONGS["夏のFree&Easy"].title,
      key: SONGS["夏のFree&Easy"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONGS["何度目の青空か?"].title,
      key: SONGS["何度目の青空か?"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONGS["誰かは味方"].title,
      key: SONGS["誰かは味方"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONGS["革命の馬"].title,
      key: SONGS["革命の馬"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONGS["僕がいる場所"].title,
      key: SONGS["僕がいる場所"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONGS["あなたのために弾きたい"].title,
      key: SONGS["あなたのために弾きたい"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONGS["他の星から"].title,
      key: SONGS["他の星から"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONGS["私のために 誰かのために"].title,
      key: SONGS["私のために 誰かのために"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONGS["せっかちなかたつむり"].title,
      key: SONGS["せっかちなかたつむり"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONGS["涙がまだ悲しみだった頃"].title,
      key: SONGS["涙がまだ悲しみだった頃"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONGS["無口なライオン"].title,
      key: SONGS["無口なライオン"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONGS["世界で一番 孤独なLover"].title,
      key: SONGS["世界で一番 孤独なLover"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONGS["あの日 僕は咄嗟に嘘をついた"].title,
      key: SONGS["あの日 僕は咄嗟に嘘をついた"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONGS["13日の金曜日"].title,
      key: SONGS["13日の金曜日"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONGS["失いたくないから"].title,
      key: SONGS["失いたくないから"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONGS["ダンケシェーン"].title,
      key: SONGS["ダンケシェーン"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONGS["傾斜する"].title,
      key: SONGS["傾斜する"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 27,
      title: SONGS["なぞの落書き"].title,
      key: SONGS["なぞの落書き"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 28,
      title: SONGS["自由の彼方"].title,
      key: SONGS["自由の彼方"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 29,
      title: SONGS["ひとりよがり"].title,
      key: SONGS["ひとりよがり"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

export const albums: IAlbums = {
  [imagaomoideninarumade.title]: imagaomoideninarumade,
  [bokudakenokimi.title]: bokudakenokimi,
  [umaretekara.title]: umaretekara,
  [sorezorenoisu.title]: sorezorenoisu,
  [tomeinairo.title]: tomeinairo,
};
