import { IAlbum, IAlbums } from "../models/IAlbum";
import { CdType, FocusPerformersType, SongType, SONG_TITLES } from "../utils/constants";

const imagaomoideninarumade: IAlbum = {
  title: "今が思い出になるまで",
  number: "4",
  release: "2019-04-17",
  hasArtworks: true,
  artworks: {
    [CdType.L]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.A]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.B]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.T]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONG_TITLES["ありがちな恋愛"].title,
      key: SONG_TITLES["ありがちな恋愛"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Lead,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONG_TITLES["逃げ水"].title,
      key: SONG_TITLES["逃げ水"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONG_TITLES["いつかできるから今日できる"].title,
      key: SONG_TITLES["いつかできるから今日できる"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONG_TITLES["シンクロニシティ"].title,
      key: SONG_TITLES["シンクロニシティ"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONG_TITLES["ジコチューで行こう!"].title,
      key: SONG_TITLES["ジコチューで行こう!"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONG_TITLES["帰り道は遠回りしたくなる"].title,
      key: SONG_TITLES["帰り道は遠回りしたくなる"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONG_TITLES["アンダー"].title,
      key: SONG_TITLES["アンダー"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONG_TITLES["My rule"].title,
      key: SONG_TITLES["My rule"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONG_TITLES["新しい世界"].title,
      key: SONG_TITLES["新しい世界"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONG_TITLES["三角の空き地"].title,
      key: SONG_TITLES["三角の空き地"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONG_TITLES["日常"].title,
      key: SONG_TITLES["日常"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONG_TITLES["もし君がいなければ"].title,
      key: SONG_TITLES["もし君がいなければ"].key,
      inCdType: [CdType.L],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONG_TITLES["キスの手裏剣"].title,
      key: SONG_TITLES["キスの手裏剣"].key,
      inCdType: [CdType.L],
      type: SongType.FourthGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONG_TITLES["Against"].title,
      key: SONG_TITLES["Against"].key,
      inCdType: [CdType.L],
      type: SongType.FirstGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONG_TITLES["つづく"].title,
      key: SONG_TITLES["つづく"].key,
      inCdType: [CdType.L],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONG_TITLES["頬杖をついては眠れない"].title,
      key: SONG_TITLES["頬杖をついては眠れない"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONG_TITLES["ぽっち党"].title,
      key: SONG_TITLES["ぽっち党"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONG_TITLES["僕の衝動"].title,
      key: SONG_TITLES["僕の衝動"].key,
      inCdType: [CdType.A],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONG_TITLES["スカウトマン"].title,
      key: SONG_TITLES["スカウトマン"].key,
      inCdType: [CdType.A],
      type: SongType.SecondGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONG_TITLES["さゆりんご募集中"].title,
      key: SONG_TITLES["さゆりんご募集中"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONG_TITLES["ゴルゴンゾーラ"].title,
      key: SONG_TITLES["ゴルゴンゾーラ"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONG_TITLES["トキトキメキメキ"].title,
      key: SONG_TITLES["トキトキメキメキ"].key,
      inCdType: [CdType.B],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONG_TITLES["未来の答え"].title,
      key: SONG_TITLES["未来の答え"].key,
      inCdType: [CdType.B],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONG_TITLES["もうすぐ～ザンビ伝説～"].title,
      key: SONG_TITLES["もうすぐ～ザンビ伝説～"].key,
      inCdType: [CdType.T],
      type: SongType.Special,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONG_TITLES["キャラバンは眠らない"].title,
      key: SONG_TITLES["キャラバンは眠らない"].key,
      inCdType: [CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONG_TITLES["ライブ神"].title,
      key: SONG_TITLES["ライブ神"].key,
      inCdType: [CdType.T],
      type: SongType.SecondGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 27,
      title: SONG_TITLES["自分じゃない感じ"].title,
      key: SONG_TITLES["自分じゃない感じ"].key,
      inCdType: [CdType.T],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

const bokudakenokimi: IAlbum = {
  title: "僕だけの君〜Under Super Best〜",
  number: "U",
  release: "2018-01-10",
  hasArtworks: true,
  artworks: {
    [CdType.L1]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.L2]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.T]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONG_TITLES["左胸の勇気"].title,
      key: SONG_TITLES["左胸の勇気"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONG_TITLES["狼に口笛を"].title,
      key: SONG_TITLES[ "狼に口笛を"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONG_TITLES["涙がまだ悲しみだった頃"].title,
      key: SONG_TITLES["涙がまだ悲しみだった頃"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONG_TITLES["春のメロディー"].title,
      key: SONG_TITLES["春のメロディー"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONG_TITLES["13日の金曜日"].title,
      key: SONG_TITLES["13日の金曜日"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONG_TITLES["扇風機"].title,
      key: SONG_TITLES["扇風機"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONG_TITLES["初恋の人を今でも"].title,
      key: SONG_TITLES["初恋の人を今でも"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONG_TITLES["生まれたままで"].title,
      key: SONG_TITLES["生まれたままで"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONG_TITLES["ここにいる理由"].title,
      key: SONG_TITLES["ここにいる理由"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONG_TITLES["あの日 僕は咄嗟に嘘をついた"].title,
      key: SONG_TITLES["あの日 僕は咄嗟に嘘をついた"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONG_TITLES["君は僕と会わない方がよかったのかな"].title,
      key: SONG_TITLES["君は僕と会わない方がよかったのかな"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONG_TITLES["別れ際、もっと好きになる"].title,
      key: SONG_TITLES["別れ際、もっと好きになる"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONG_TITLES["嫉妬の権利"].title,
      key: SONG_TITLES["嫉妬の権利"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONG_TITLES["不等号"].title,
      key: SONG_TITLES["不等号"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONG_TITLES["シークレットグラフィティー"].title,
      key: SONG_TITLES["シークレットグラフィティー"].key,
      inCdType: [CdType.L1],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONG_TITLES["ブランコ"].title,
      key: SONG_TITLES["ブランコ"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONG_TITLES["風船は生きている"].title,
      key: SONG_TITLES["風船は生きている"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONG_TITLES["アンダー"].title,
      key: SONG_TITLES["アンダー"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONG_TITLES["My rule"].title,
      key: SONG_TITLES["My rule"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONG_TITLES["自由の彼方"].title,
      key: SONG_TITLES["自由の彼方"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONG_TITLES["欲望のリインカーネーション"].title,
      key: SONG_TITLES["欲望のリインカーネーション"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONG_TITLES["君が扇いでくれた"].title,
      key: SONG_TITLES["君が扇いでくれた"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONG_TITLES["自分のこと"].title,
      key: SONG_TITLES["自分のこと"].key,
      inCdType: [CdType.L2],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONG_TITLES["自惚れビーチ"].title,
      key: SONG_TITLES["自惚れビーチ"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONG_TITLES["その女"].title,
      key: SONG_TITLES["その女"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONG_TITLES["誰よりそばにいたい"].title,
      key: SONG_TITLES["誰よりそばにいたい"].key,
      inCdType: [CdType.L2],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

const umaretekara: IAlbum = {
  title: "生まれてから初めて見た夢",
  number: "3",
  release: "2017-05-24",
  hasArtworks: true,
  artworks: {
    [CdType.A]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.B]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.L]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.T]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONG_TITLES["裸足でSummer"].title,
      key: SONG_TITLES["裸足でSummer"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONG_TITLES["サヨナラの意味"].title,
      key: SONG_TITLES["サヨナラの意味"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONG_TITLES["インフルエンサー"].title,
      key: SONG_TITLES["インフルエンサー"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONG_TITLES["シークレットグラフィティー"].title,
      key: SONG_TITLES["シークレットグラフィティー"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONG_TITLES["ブランコ"].title,
      key: SONG_TITLES["ブランコ"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONG_TITLES["風船は生きている"].title,
      key: SONG_TITLES["風船は生きている"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONG_TITLES["スカイダイビング"].title,
      key: SONG_TITLES["スカイダイビング"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONG_TITLES["三番目の風"].title,
      key: SONG_TITLES["三番目の風"].key,
      inCdType: [CdType.L, CdType.A, CdType.B, CdType.T],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONG_TITLES["君が扇いでくれた"].title,
      key: SONG_TITLES["君が扇いでくれた"].key,
      inCdType: [CdType.L],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONG_TITLES["思い出ファースト"].title,
      key: SONG_TITLES["思い出ファースト"].key,
      inCdType: [CdType.L],
      type: SongType.ThirdGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONG_TITLES["設定温度"].title,
      key: SONG_TITLES["設定温度"].key,
      inCdType: [CdType.L],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONG_TITLES["孤独な青空"].title,
      key: SONG_TITLES["孤独な青空"].key,
      inCdType: [CdType.L],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONG_TITLES["僕だけの光"].title,
      key: SONG_TITLES["僕だけの光"].key,
      inCdType: [CdType.L],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONG_TITLES["人生を考えたくなる"].title,
      key: SONG_TITLES["人生を考えたくなる"].key,
      inCdType: [CdType.L],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONG_TITLES["意外BREAK"].title,
      key: SONG_TITLES["意外BREAK"].key,
      inCdType: [CdType.L],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONG_TITLES["Rewindあの日"].title,
      key: SONG_TITLES["Rewindあの日"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONG_TITLES["ごめんね、スムージー"].title,
      key: SONG_TITLES["ごめんね、スムージー"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONG_TITLES["醜い私"].title,
      key: SONG_TITLES["醜い私"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONG_TITLES["オフショアガール"].title,
      key: SONG_TITLES["オフショアガール"].key,
      inCdType: [CdType.A],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONG_TITLES["君に贈る花がない"].title,
      key: SONG_TITLES["君に贈る花がない"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONG_TITLES["白米様"].title,
      key: SONG_TITLES["白米様"].key,
      inCdType: [CdType.A],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONG_TITLES["硬い殻のように抱きしめたい"].title,
      key: SONG_TITLES["硬い殻のように抱きしめたい"].key,
      inCdType: [CdType.B],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONG_TITLES["満月が消えた"].title,
      key: SONG_TITLES["満月が消えた"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONG_TITLES["ワタボコリ"].title,
      key: SONG_TITLES["ワタボコリ"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONG_TITLES["ないものねだり"].title,
      key: SONG_TITLES["ないものねだり"].key,
      inCdType: [CdType.B],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONG_TITLES["Another Ghost"].title,
      key: SONG_TITLES["Another Ghost"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 27,
      title: SONG_TITLES["あの教室"].title,
      key: SONG_TITLES["あの教室"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 28,
      title: SONG_TITLES["流星ディスコティック"].title,
      key: SONG_TITLES["流星ディスコティック"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 29,
      title: SONG_TITLES["忘却と美学"].title,
      key: SONG_TITLES["忘却と美学"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 30,
      title: SONG_TITLES["2度目のキスから"].title,
      key: SONG_TITLES["2度目のキスから"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 31,
      title: SONG_TITLES["命の真実 ミュージカル「林檎売りとカメムシ」"].title,
      key: SONG_TITLES["命の真実 ミュージカル「林檎売りとカメムシ」"].key,
      inCdType: [CdType.T],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 32,
      title: SONG_TITLES["行くあてのない僕たち"].title,
      key: SONG_TITLES["行くあてのない僕たち"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 33,
      title: SONG_TITLES["当たり障りのない話"].title,
      key: SONG_TITLES["当たり障りのない話"].key,
      inCdType: [CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

const sorezorenoisu: IAlbum = {
  title: "それぞれの椅子",
  number: "2",
  release: "2016-05-25",
  hasArtworks: true,
  artworks: {
    [CdType.A]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.B]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.C]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.D]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.T]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONG_TITLES["命は美しい"].title,
      key: SONG_TITLES["命は美しい"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONG_TITLES["太陽ノック"].title,
      key: SONG_TITLES["太陽ノック"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONG_TITLES["今、話したい誰かがいる"].title,
      key: SONG_TITLES["今、話したい誰かがいる"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONG_TITLES["きっかけ"].title,
      key: SONG_TITLES["きっかけ"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONG_TITLES["太陽に口説かれて"].title,
      key: SONG_TITLES["太陽に口説かれて"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONG_TITLES["欲望のリインカーネーション"].title,
      key: SONG_TITLES["欲望のリインカーネーション"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONG_TITLES["悲しみの忘れ方"].title,
      key: SONG_TITLES["悲しみの忘れ方"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONG_TITLES["空気感"].title,
      key: SONG_TITLES["空気感"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONG_TITLES["光合成希望"].title,
      key: SONG_TITLES["光合成希望"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONG_TITLES["無表情"].title,
      key: SONG_TITLES["無表情"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONG_TITLES["あらかじめ語られるロマンス"].title,
      key: SONG_TITLES["あらかじめ語られるロマンス"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONG_TITLES["隙間"].title,
      key: SONG_TITLES["隙間"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONG_TITLES["急斜面"].title,
      key: SONG_TITLES["急斜面"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONG_TITLES["羽根の記憶"].title,
      key: SONG_TITLES["羽根の記憶"].key,
      inCdType: [CdType.A, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONG_TITLES["乃木坂の詩"].title,
      key: SONG_TITLES["乃木坂の詩"].key,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONG_TITLES["Threefold choice"].title,
      key: SONG_TITLES["Threefold choice"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONG_TITLES["低体温のキス"].title,
      key: SONG_TITLES["低体温のキス"].key,
      inCdType: [CdType.B],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONG_TITLES["遥かなるブータン"].title,
      key: SONG_TITLES["遥かなるブータン"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONG_TITLES["ポピパッパパー"].title,
      key: SONG_TITLES["ポピパッパパー"].key,
      inCdType: [CdType.B],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONG_TITLES["制服を脱いでサヨナラを…"].title,
      key: SONG_TITLES["制服を脱いでサヨナラを…"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONG_TITLES["憂鬱と風船ガム"].title,
      key: SONG_TITLES["憂鬱と風船ガム"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONG_TITLES["立ち直り中"].title,
      key: SONG_TITLES["立ち直り中"].key,
      inCdType: [CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONG_TITLES["失恋したら、顔を洗え!"].title,
      key: SONG_TITLES["失恋したら、顔を洗え!"].key,
      inCdType: [CdType.C],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONG_TITLES["かき氷の片想い"].title,
      key: SONG_TITLES["かき氷の片想い"].key,
      inCdType: [CdType.C],
      type: SongType.SecondGeneration,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONG_TITLES["大人への近道"].title,
      key: SONG_TITLES["大人への近道"].key,
      inCdType: [CdType.C],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONG_TITLES["君は僕と会わない方がよかったのかな"].title,
      key: SONG_TITLES["君は僕と会わない方がよかったのかな"].key,
      inCdType: [CdType.C],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 27,
      title: SONG_TITLES["別れ際、もっと好きになる"].title,
      key: SONG_TITLES["別れ際、もっと好きになる"].key,
      inCdType: [CdType.C],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 28,
      title: SONG_TITLES["嫉妬の権利"].title,
      key: SONG_TITLES["嫉妬の権利"].key,
      inCdType: [CdType.C],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 29,
      title: SONG_TITLES["不等号"].title,
      key: SONG_TITLES["不等号"].key,
      inCdType: [CdType.C],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 30,
      title: SONG_TITLES["環状六号線"].title,
      key: SONG_TITLES["環状六号線"].key,
      inCdType: [CdType.D],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 31,
      title: SONG_TITLES["口約束"].title,
      key: SONG_TITLES["口約束"].key,
      inCdType: [CdType.D],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 32,
      title: SONG_TITLES["ロマンティックいか焼き"].title,
      key: SONG_TITLES["ロマンティックいか焼き"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 33,
      title: SONG_TITLES["ハウス!"].title,
      key: SONG_TITLES["ハウス!"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 34,
      title: SONG_TITLES["そんなバカな…"].title,
      key: SONG_TITLES["そんなバカな…"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 35,
      title: SONG_TITLES["シャキイズム"].title,
      key: SONG_TITLES["シャキイズム"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 36,
      title: SONG_TITLES["ロマンスのスタート"].title,
      key: SONG_TITLES["ロマンスのスタート"].key,
      inCdType: [CdType.D],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

const tomeinairo: IAlbum = {
  title: "透明な色",
  number: "1",
  release: "2015-01-27",
  hasArtworks: true,
  artworks: {
    [CdType.A]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.B]: {
      large: "",
      medium: "",
      small: "",
    },
    [CdType.C]: {
      large: "",
      medium: "",
      small: "",
    },
  },
  shopping: [
    {
      title: "iTunes",
      url: "",
    },
  ],
  songs: [
    {
      number: 1,
      title: SONG_TITLES["OVERTURE"].title,
      key: SONG_TITLES["OVERTURE"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 2,
      title: SONG_TITLES["ぐるぐるカーテン"].title,
      key: SONG_TITLES["ぐるぐるカーテン"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 3,
      title: SONG_TITLES["おいでシャンプー"].title,
      key: SONG_TITLES["おいでシャンプー"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 4,
      title: SONG_TITLES["走れ!Bicycle"].title,
      key: SONG_TITLES["走れ!Bicycle"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 5,
      title: SONG_TITLES["制服のマネキン"].title,
      key: SONG_TITLES["制服のマネキン"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 6,
      title: SONG_TITLES["君の名は希望"].title,
      key: SONG_TITLES["君の名は希望"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 7,
      title: SONG_TITLES["ガールズルール"].title,
      key: SONG_TITLES["ガールズルール"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 8,
      title: SONG_TITLES["バレッタ"].title,
      key: SONG_TITLES["バレッタ"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 9,
      title: SONG_TITLES["気づいたら片想い"].title,
      key: SONG_TITLES["気づいたら片想い"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 10,
      title: SONG_TITLES["夏のFree&Easy"].title,
      key: SONG_TITLES["夏のFree&Easy"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 11,
      title: SONG_TITLES["何度目の青空か?"].title,
      key: SONG_TITLES["何度目の青空か?"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Title,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 12,
      title: SONG_TITLES["誰かは味方"].title,
      key: SONG_TITLES["誰かは味方"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 13,
      title: SONG_TITLES["革命の馬"].title,
      key: SONG_TITLES["革命の馬"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 14,
      title: SONG_TITLES["僕がいる場所"].title,
      key: SONG_TITLES["僕がいる場所"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 15,
      title: SONG_TITLES["あなたのために弾きたい"].title,
      key: SONG_TITLES["あなたのために弾きたい"].key,
      inCdType: [CdType.A, CdType.B, CdType.C],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 16,
      title: SONG_TITLES["他の星から"].title,
      key: SONG_TITLES["他の星から"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 17,
      title: SONG_TITLES["私のために 誰かのために"].title,
      key: SONG_TITLES["私のために 誰かのために"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 18,
      title: SONG_TITLES["せっかちなかたつむり"].title,
      key: SONG_TITLES["せっかちなかたつむり"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 19,
      title: SONG_TITLES["涙がまだ悲しみだった頃"].title,
      key: SONG_TITLES["涙がまだ悲しみだった頃"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 20,
      title: SONG_TITLES["無口なライオン"].title,
      key: SONG_TITLES["無口なライオン"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 21,
      title: SONG_TITLES["世界で一番 孤独なLover"].title,
      key: SONG_TITLES["世界で一番 孤独なLover"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 22,
      title: SONG_TITLES["あの日 僕は咄嗟に嘘をついた"].title,
      key: SONG_TITLES["あの日 僕は咄嗟に嘘をついた"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 23,
      title: SONG_TITLES["13日の金曜日"].title,
      key: SONG_TITLES["13日の金曜日"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 24,
      title: SONG_TITLES["失いたくないから"].title,
      key: SONG_TITLES["失いたくないから"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 25,
      title: SONG_TITLES["ダンケシェーン"].title,
      key: SONG_TITLES["ダンケシェーン"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 26,
      title: SONG_TITLES["傾斜する"].title,
      key: SONG_TITLES["傾斜する"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Coupling,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 27,
      title: SONG_TITLES["なぞの落書き"].title,
      key: SONG_TITLES["なぞの落書き"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Unit,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 28,
      title: SONG_TITLES["自由の彼方"].title,
      key: SONG_TITLES["自由の彼方"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Under,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
    {
      number: 29,
      title: SONG_TITLES["ひとりよがり"].title,
      key: SONG_TITLES["ひとりよがり"].key,
      inCdType: [CdType.A, CdType.B],
      type: SongType.Solo,
      artwork: { large: "", medium: "", small: "" },
      focusPerformers: {
        type: FocusPerformersType.None,
        name: [],
      },
    },
  ],
};

export const albums: IAlbums = {
  [imagaomoideninarumade.title]: imagaomoideninarumade,
  [bokudakenokimi.title]: bokudakenokimi,
  [umaretekara.title]: umaretekara,
  [sorezorenoisu.title]: sorezorenoisu,
  [tomeinairo.title]: tomeinairo,
};
